### ISSUE TITLE
switchboard restart loop

### ISSUE THREAD

**Issue by JiTmun** [thinkst/canarytokens#132]
Hello,

# Description
After the docker compose, the switchboard succeed to build and start but logs shows that each 20 second the container restart, see error message and switchboard below. Any hint about solving this issue? What surprises me is I am not using the https docker version, but still the error is about certificate generation.
Thanks for the help 

# Error message

 Failed to load application: Server Certificate generation failed. Cert:None

Exception: [('X509 V3 routines', 'X509V3_parse_list', 'invalid null value'), ('X509 V3 routines', 'do_ext_nconf', 'invalid extension string'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "switchboard.tac", line 83, in <module>
    switchboard=switchboard)
  File "/srv/channel_input_mtls.py", line 238, in __init__
    self.service = SSLServer(port, factory, self._get_ssl_context())
  File "/srv/channel_input_mtls.py", line 276, in _get_ssl_context
    raise e
exceptions.Exception: Server Certificate generation failed. Cert:None

Exception: [('X509 V3 routines', 'X509V3_parse_list', 'invalid null value'), ('X509 V3 routines', 'do_ext_nconf', 'invalid extension string'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]

Failed to load application: Server Certificate generation failed. Cert:None

## Switchboard used
#CANARY_MAILGUN_DOMAIN_NAME=
#CANARY_MAILGUN_API_KEY=
#CANARY_MANDRILL_API_KEY=
#CANARY_SENDGRID_API_KEY=
#CANARY_PUBLIC_IP=
CANARY_PUBLIC_DOMAIN=canarytoken.test
CANARY_WG_PRIVATE_KEY_SEED=RRFMgjmCANz9rQhup1bODGBbpBYVZSs7EuPaNObOpbU=
CANARY_ALERT_EMAIL_FROM_ADDRESS=
CANARY_ALERT_EMAIL_FROM_DISPLAY=
CANARY_ALERT_EMAIL_SUBJECT=
#CANARY_IPINFO_API_KEY=

CANARY_TOKEN_RETURN=fortune

CANARY_WEB_IMAGE_UPLOAD_PATH=/uploads

LOG_FILE=switchboard.log

#Default protocol to use in notification links. If you don't use LetsEncrypt, set to http
PROTOCOL=http

**Comment by JiTmun** [comment]
moved to https://github.com/thinkst/canarytokens-docker/issues/107
